### ISSUE TITLE
java.lang.NoSuchMethodError: com.bigdata.rdf.sail.BigdataSailRepository.getDatabase()Lcom/bigdata/rdf/store/AbstractTripleStore

### ISSUE THREAD

**Issue by imhy** [blazegraph/tinkerpop3#6]
Hi!
When I try to 
File file = new File("/blaze/bg1.jrnl");
final String journal = file.getAbsolutePath();
final BigdataSailRepository repo = BasicRepositoryProvider.open(journal);
graph = BlazeGraphEmbedded.open(repo);

I get error:

java.lang.NoSuchMethodError: com.bigdata.rdf.sail.BigdataSailRepository.getDatabase()Lcom/bigdata/rdf/store/AbstractTripleStore;
	at com.blazegraph.gremlin.embedded.BlazeGraphEmbedded.open(BlazeGraphEmbedded.java:180)
	at com.blazegraph.gremlin.embedded.BlazeGraphEmbedded.open(BlazeGraphEmbedded.java:163)

I`m using maven dependencies
 <dependency>
            <groupId>com.blazegraph</groupId>
            <artifactId>bigdata-core</artifactId>
            <version>2.1.4</version>
        </dependency>
        <dependency>
            <groupId>com.blazegraph</groupId>
            <artifactId>blazegraph-gremlin</artifactId>
            <version>1.0.0</version>
        </dependency>

What I`m doing wrong?

**Comment by WolfgangFahl** [comment]
see #8 and #9 
The fork at BITPlan will work.
